services:
  api:
    image: lpr-fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    # mount .env file
    env_file:
      - .env
    # mount real path wiith container path
    volumes:
      - ./model:/app/model:ro
    restart: unless-stopped
